version: '2'
services:

  mysql:
    container_name: mysql
    restart: always
    build:
      context: .
    hostname: mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;'
    env_file:
      - ./.env_mysql
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/my.cnf

